// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class LocationImage
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string Path { get; set; }

        public virtual Location Location { get; set; }
    }
}