// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class Location
    {
        public Location()
        {
            LocationBranch = new HashSet<LocationBranch>();
            LocationImage = new HashSet<LocationImage>();
            LocationOrder = new HashSet<LocationOrder>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string ContactPhone { get; set; }
        public string Area { get; set; }
        public string ImagePath { get; set; }
        public string Website { get; set; }

        public virtual ICollection<LocationBranch> LocationBranch { get; set; }
        public virtual ICollection<LocationImage> LocationImage { get; set; }
        public virtual ICollection<LocationOrder> LocationOrder { get; set; }
    }
}