// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class LocationOrder
    {
        public int Id { get; set; }
        public int LocationBranchId { get; set; }
        public int MemberId { get; set; }
        public int Price { get; set; }
        public DateTime Date { get; set; }
        public DateTime Time { get; set; }
        public int? LocationBranchId1 { get; set; }

        public virtual Location LocationBranch { get; set; }
        public virtual LocationBranch LocationBranchId1Navigation { get; set; }
        public virtual Member Member { get; set; }
    }
}