// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class Member
    {
        public Member()
        {
            LocationOrder = new HashSet<LocationOrder>();
            ProductsCart = new HashSet<ProductsCart>();
            ProductsOrder = new HashSet<ProductsOrder>();
        }

        public int Id { get; set; }
        public int IsActive { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public DateTime CreateTime { get; set; }
        public string ImagePath { get; set; }
        public int Role { get; set; }

        public virtual ICollection<LocationOrder> LocationOrder { get; set; }
        public virtual ICollection<ProductsCart> ProductsCart { get; set; }
        public virtual ICollection<ProductsOrder> ProductsOrder { get; set; }
    }
}