// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class ProductsCart
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int ProductsId { get; set; }
        public int Count { get; set; }

        public virtual Member Member { get; set; }
        public virtual Products Products { get; set; }
    }
}