// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsCenter.Models.Entity
{
    public partial class Products
    {
        public Products()
        {
            ProductsCart = new HashSet<ProductsCart>();
        }

        public int ProductsId { get; set; }
        public int ItemId { get; set; }
        public string ProductsName { get; set; }
        public int ProductsPrice { get; set; }
        public DateTime ProductsDateTime { get; set; }
        public int ProductsInventory { get; set; }
        public string ProductsImagePath { get; set; }

        public virtual Item Item { get; set; }
        public virtual ICollection<ProductsCart> ProductsCart { get; set; }
    }
}